spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql:
        format_sql:
logging:
  level:
    org.hibernate.sql:
    org.hibernate.orm.jdbc.bind: